name: Idee vorschlagen / Suggest an improvement
description: Schlage eine öffentlich diskutierbare Verbesserung für Bring Me Sun vor.
title: "[Idea]: "
labels: ["external", "enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem soll gelöst werden? / What problem should be solved?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Vorschlag / Proposed improvement
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Datenschutz / Privacy
      options:
        - label: Ich habe keine personenbezogenen oder vertraulichen Daten eingefügt.
          required: true